version: "3.9"
services:
  iris-ml:
    image: ghcr.io/mrhari76/docker-swarm-mlops-practice:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure